# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model: 
#    + IONet
#    + descriptor upsampling 
#    + cross-border keypoints
#    + descriptor loss

model:
    params:
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
    checkpoint_path: '/home/rashik/workspace/simplicity/KP2D/data' 

wandb:
    dry_run: True
    project: 'kp2d_train_1'

datasets:
    train:
        path: '/mnt/Enterprise/PUBLIC_DATASETS/coco/coco_train'
        batch_size: 16
        num_workers: 8
    val:
        path: '/mnt/Enterprise/PUBLIC_DATASETS/HPatches'
